### ISSUE TITLE
unrecognised command

### ISSUE THREAD

**Issue by 6R1M4C3** [yaroslaff/nudecrawler#2]
After installing this either with pip or pip +git when you come to use it all you receive is "not recognized as an internal or external command" how to rectify this?

**Comment by yaroslaff** [comment]
probably it's not an nudecrawler issue, your OS cannot find nudecrawler binary to run. 
nudecrawler binary is in same directory as other scripts like detect-image-nsfw-api.py

If you installed as root, it should be in /usr/local/bin/
if as ordinary user, it could be inside your $HOME, ~/.local/bin/ (for Debian)

find where it is, add this directory to PATH and it should work. :-)

**Comment by 6R1M4C3** [comment]
what is the scripts file called so I can look for its location please / I'm assuming this cant be used on windows maybe I need to use linux

**Comment by yaroslaff** [comment]
main script name is exactly "nudecrawler". 
but this is same name as package, so maybe will be harder to find. You may try to find "detect-image-nsfw-api.py", it must be in same directory as nudecrawler.

**Comment by yaroslaff** [comment]
nudepy is script for one of packages that nudecrawler is using (one of requirements). Maybe you installed nudepy, but nudecrawler itself failed to install?
Also, some people reported it worked with python 3.9 for them, but not with 3.10-3.11

**Comment by just-mironov** [comment]
For my case, this helped: `export PATH="$HOME/nudecrawler/build/scripts-3.10/:$PATH"`

**Comment by 6R1M4C3** [comment]
> main script name is exactly "nudecrawler". but this is same name as package, so maybe will be harder to find. You may try to find "[detect-image-nsfw-api.py](http://detect-image-nsfw-api.py)", it must be in same directory as nudecrawler.

i found the files and the scripts they are already in my path as other applications work but the nudecrawler.file (nudecrawler) is still is an unrecognised command and I'm using 3.9 now as well to test

**Comment by yaroslaff** [comment]
what OS do you have?

try command: python PATH/TO/nudecrawler
(or python3, python3.9)

**Comment by 6R1M4C3** [comment]
> what OS do you have? try command: python PATH/TO/nudecrawler (or python3, python3.9)

Hello, I am currently using Windows, I have the Python scripts folder in the paths of the environment variable, the file called nudecrawler is in this location but when used as a command it does not register it, I can see the file is there it has no extension like the rest of the scripts but its there it just doesn't register as a command.

**Comment by yaroslaff** [comment]
So, "Python PATH/TO/nudecrawler" should work (Python.exe should be in your PATH most likely).

**Comment by 6R1M4C3** [comment]
> So, "Python PATH/TO/nudecrawler" should work (Python.exe should be in your PATH most likely).

Ok so manually using the path in the command works now, just cant get the path to naturally work without using it in the command. thank you

**Comment by yaroslaff** [comment]
Great! :-)

**Comment by 6R1M4C3** [comment]
> Great! :-)

The use of other detectors cant be used though is there a way to manually tell it the location of the detector to use because for some reason the path isn't automatically accepted

**Comment by yaroslaff** [comment]
Maybe as workaround you can make a .bat file which will call "python path/to/detector-scriptpy $1" and use it as detector.
But, little spoiler - in few days I plan to release a Docker version of nudecrawler, maybe it will be easier to use on Windows.
