### ISSUE TITLE
json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes

### ISSUE THREAD

**Issue by jeffscrum** [yaroslaff/nudecrawler#5]
The program interrupts with an error:

```
Traceback (most recent call last):
  File "/usr/local/bin/nudecrawler", line 505, in <module>
    main()
  File "/usr/local/bin/nudecrawler", line 436, in main
    cache.load(stats['cache_path'])
  File "/usr/local/lib/python3.9/site-packages/nudecrawler/cache.py", line 47, in load
    cache = json.load(fh)
  File "/usr/local/lib/python3.9/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/usr/local/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.9/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 108440 column 5 (char 9056873)
```
stats.json -- https://pastebin.com/jtCCBrML

`--bugreport` not work
nudecrawler dockered 0.3.16

**Comment by yaroslaff** [comment]
yes, bugreport work only in specific locations where special code is written, where we expecting error.
Check, if your cache file (`cache.json`) is valid JSON? e.g.
~~~
cat .nudecrawler/cache.json | jq
~~~
Most likely, it's damaged (e.g. nudecrawler was stopped when it was writing cache on disk, so file is damaged).

Lets confirm/reject this idea, and then will think how to prevent it in future.

**Comment by yaroslaff** [comment]
Also, please check tail of cache.json, does it looks like incomplete JSON or not? my cache.json ends with:
```
xenon@golf:~$ tail -n 3 .nudecrawler/cache.json ; echo
    "7461110faad66cd5be71bbe9cdfb4ecbcca2498c": false
  }
}

```

**Comment by jeffscrum** [comment]
Yes, it's damaged

```
$ cat cache.json | jq
parse error: Unfinished JSON term at EOF at line 108440, column 4
```
and the file ends } }

```
"4d953cd48198680a92e37a1851e5d223f54009fa": true,
"594a37ecada9d19af120fc20d907342797c77159": true,
$
```

can I just add }} at the end?

**Comment by yaroslaff** [comment]
Hrm... I'm not sure (because if it will check page with URL from cache, it will find URL in cache and get sum for it, but then it could not resolve sum to boolean verdict  (True or False) because it's missed in cache). But why not to try?

**Comment by jeffscrum** [comment]
Yes, you can add }} at the end of file and remove the comma (,) at the end of the previous line.
Problem solved, thanks
