### ISSUE TITLE
I can't run it :(

### ISSUE THREAD

**Issue by moemoekyum** [yaroslaff/nudecrawler#7]
When running "nudecrawler sasha-grey" it only generates a script, any suggestions on how to run it?

**Comment by yaroslaff** [comment]
What do you mean "it only generates a script"? Can you show me exactly how you run it and what does it print? Also, try "-a" option (to print all found pages, without nudity detection) and try docker version, maybe it will run better for you, it's recommended way (docker container goes with all proper packages installed)
