### ISSUE TITLE
Not an issue just a question

### ISSUE THREAD

**Issue by tuankg1028** [yaroslaff/nudecrawler#8]
Hello, 
Can we use this tool to download images from URLs that are returned to a local folder on computer? 
Thanks

**Comment by yaroslaff** [comment]
Thank you for question.
I did not needed it myself, I just opened browser to see it. And I do not want to make this tool overloaded with lot of functions/arguments, but if you need this feature, it's easy to achive with your own custom detector.

Take any detector from nudecrawler (bin/detect-image-*.sh, detect-image-aid.py for example), and there you have:
~~~python
def main():
    image_path = sys.argv[1]
~~~
copy that image to where you want.

Or make dirty patch somewhere in `is_nude()` (page.py line 284), `do_detect_image()` or in `RemoteImage.__del__()`
~~~python
    def __del__(self):
        if self.path:
            os.unlink(self.path)
~~~

Just do not unlink, and it will keep all temporary files.

**Comment by tuankg1028** [comment]
Thank you for your response 
maybe I can customize some codes for my purpose, one more question could I know where all temporary files are stored?

**Comment by yaroslaff** [comment]
In `RemoteImage.__init__` there is an code:

~~~python
 with tempfile.NamedTemporaryFile(suffix=suffix, delete=False) as tmp:
            self.path = tmp.name
            tmp.file.write(r.content)
~~~
Usually, it's in `/tmp`, but you may add `prefix=` to keep it somewhere else.
